feeds_migrate.importer.*:
  type: config_entity
  label: "Feeds Migrate Importer"
  mapping:
    id:
      type: string
      label: "ID"
    label:
      type: label
      label: "Label"
    source:
      type: string
      label: "Migration Source"
    importPeriod:
      type: integer
      label: "Import periodicity"
    existing:
      type: integer
      label: "Existing items"
    orphans:
      type: string
      label: "Orphaned Items"
    dataFetcherSettings:
      type: sequence
    authSettings:
      type: sequence
    lastRan:
      type: integer
      label: "Queued up for cron"

# Schema for the configuration files of the Migrate Plus module.

feeds_migrate.feeds_migration.*:
  type: config_entity
  label: 'Feeds Migration'
  mapping:
    id:
      type: string
      label: 'ID'
    class:
      type: string
      label: 'Class'
    field_plugin_method:
      type: string
      label: 'Field Plugin Method'
    cck_plugin_method:
      type: string
      label: 'BC layer for Field Plugin Method'
    migration_tags:
      type: sequence
      label: 'Migration Tags'
      sequence:
        type: string
        label: 'Tag'
    migration_group:
      type: string
      label: 'Group'
    label:
      type: label
      label: 'Label'
    source:
      type: migrate_plus.source.[plugin]
      label: 'Source'
    process:
      type: ignore
      label: 'Process'
    destination:
      type: migrate_plus.destination.[plugin]
      label: 'Destination'
    migration_dependencies:
      type: mapping
      label: 'Dependencies'
      mapping:
        required:
          type: sequence
          label: 'Required dependencies'
          sequence:
            type: string
            label: 'Dependency'
        optional:
          type: sequence
          label: 'Optional dependencies'
          sequence:
            type: string
            label: 'Dependency'

feeds_migrate.feeds_migration_group.*:
  type: config_entity
  label: 'Feeds Migration Group'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    source_type:
      type: string
      label: 'Source type'
    module:
      type: string
      label: 'Dependent module'
    shared_configuration:
      type: ignore
      label: 'Shared migration configuration'
